theme: jekyll-theme-minimal
title: Data Science Portfolio
logo: https://geniuslifedesign.github.io/Projects.github.io/data-visualization.png
description: In this repo, you can find practical solutions to real world business problems using statistical methods and machine learning models. Projects are completed utilizating jupyter notebooks.